wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1665064448.344939
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 1
      - 16
      - 23
      4: 3.9.12
      5: 0.13.4
      8:
      - 5
aggregator:
  desc: null
  value: last
backprop_every:
  desc: null
  value: 1
bs:
  desc: null
  value: 200
data:
  desc: null
  value: wikipedia
different_new_nodes:
  desc: null
  value: false
drop_out:
  desc: null
  value: 0.1
dyrep:
  desc: null
  value: false
embedding_module:
  desc: null
  value: graph_attention
gpu:
  desc: null
  value: 0
lr:
  desc: null
  value: 0.0001
memory_dim:
  desc: null
  value: 172
memory_update_at_end:
  desc: null
  value: false
memory_updater:
  desc: null
  value: gru
message_dim:
  desc: null
  value: 100
message_function:
  desc: null
  value: identity
n_degree:
  desc: null
  value: 10
n_epoch:
  desc: null
  value: 5
n_head:
  desc: null
  value: 2
n_layer:
  desc: null
  value: 1
n_runs:
  desc: null
  value: 1
node_dim:
  desc: null
  value: 100
patience:
  desc: null
  value: 5
prefix:
  desc: null
  value: tgn-attn
randomize_features:
  desc: null
  value: false
time_dim:
  desc: null
  value: 100
uniform:
  desc: null
  value: false
use_destination_embedding_in_message:
  desc: null
  value: false
use_memory:
  desc: null
  value: true
use_source_embedding_in_message:
  desc: null
  value: false
